---
- name: CREATING USER VIA ANSIBLE
  hosts: node
  tasks:

    - name: CHECKING USER IS EXISTS OR NOT
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: PRINTITNG THE OUTPUT
      ansible.builtin.debug:
        msg: "{{output}}"
        
    - name: CREATING USER
      ansible.builtin.user:
        become: yes
        name: roboshop
        when: output.rc ! = 0
