- name: CREATING DIRECTORY IF NOT EXISTS
  hosts: node
  tasks:

  - name: CHECKING DIRECTORY EXIST OR NOT
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: PRINTING THE OUTPUT
    ansible.builtin.debug:
      msg: "{{directory}}"
    
  - when: directory.stat.exists == False
    name: CREATING A DIRECTORY
    become: yes 
    ansible.builtin.file:
      path: /app
      state: directory
   
